name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          go build -v -o "${{ github.workspace }}/build/"
          chmod +x "${{ github.workspace }}/build/server_monitoring"

      - name: "ZIP the binary directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/build"
          zip server_monitoring.zip server_monitoring
          zip -u server_monitoring.zip server_monitoring.service

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.0.5
        with:
          files: ${{ github.workspace }}/build/server_monitoring.zip

      - name: "Upload the binary file to the release"
        uses: softprops/action-gh-release@v2.0.5
        with:
          files: |
            ${{ github.workspace }}/build/server_monitoring
            ${{ github.workspace }}/build/server_monitoring.service
